# Path: phases/11-llm-engineering/04-embeddings/docs/en.md
# Lesson: Embeddings & Vector Representations
# Exercises Implementation
# This script implements the 5 exercises described in en.md to analyze metrics,
# chunk sizes, Matryoshka dimension truncation, binary quantization, and sentence-based chunking.

import math
import numpy as np
from collections import Counter
from embeddings import (
    SimpleEmbedder,
    VectorIndex,
    SemanticSearchEngine,
    cosine_similarity,
    dot_product,
    euclidean_distance,
    hamming_distance,
    binarize,
    chunk_text,
    chunk_by_sentences,
    truncate_embedding,
    SAMPLE_DOCUMENTS
)

# 5 standard queries to use across the exercises
QUERIES = [
    "What is the refund policy for enterprise customers?",
    "What are the API rate limits?",
    "How is customer data encrypted?",
    "What happens if uptime falls below the SLA?",
    "How much does the Professional plan cost?"
]

SOURCE_NAMES = [
    "refund-policy.md",
    "product-overview.md",
    "security.md",
    "api-docs.md",
    "uptime-sla.md"
]

def run_exercise_1():
    print("=" * 70)
    print("EXERCISE 1: Metric Comparison (Cosine vs Dot Product vs Euclidean)")
    print("=" * 70)
    
    # Initialize the search engine with default settings
    engine = SemanticSearchEngine(chunk_size=50, overlap=10)
    engine.index_documents(SAMPLE_DOCUMENTS, SOURCE_NAMES)
    
    disagreement_count = 0
    
    for q_idx, query in enumerate(QUERIES):
        print(f"\nQuery {q_idx + 1}: \"{query}\"")
        
        # Search using the three metrics
        cosine_res = engine.search(query, top_k=3, metric="cosine")
        dot_res = engine.search(query, top_k=3, metric="dot")
        euclidean_res = engine.search(query, top_k=3, metric="euclidean")
        
        # Extract the document/chunk text previews and indices
        cosine_ids = [r["index"] for r in cosine_res]
        dot_ids = [r["index"] for r in dot_res]
        euclidean_ids = [r["index"] for r in euclidean_res]
        
        # Check if the ordering/results differ
        agree = (cosine_ids == dot_ids == euclidean_ids)
        if not agree:
            disagreement_count += 1
            
        print(f"  - Cosine top-3 indices:    {cosine_ids}")
        print(f"  - Dot Product top-3 indices:{dot_ids}")
        print(f"  - Euclidean top-3 indices:  {euclidean_ids}")
        print(f"  - Metrics Agree: {'Yes' if agree else 'No'}")
        
        # Show scores
        print("  Scores:")
        for idx in range(3):
            c_item, d_item, e_item = cosine_res[idx], dot_res[idx], euclidean_res[idx]
            print(f"    Rank {idx+1}:")
            print(f"      Cosine:    idx={c_item['index']}, score={c_item['score']:.4f}")
            print(f"      Dot:       idx={d_item['index']}, score={d_item['score']:.4f}")
            print(f"      Euclidean: idx={e_item['index']}, score={e_item['score']:.4f}")
            
    print("\n--- Analysis Summary ---")
    print(f"Total queries with metric disagreements: {disagreement_count} / {len(QUERIES)}")
    print("Why? Since the embeddings generated by SimpleEmbedder are L2 normalized (unit length),")
    print("cosine similarity and dot product are mathematically identical (dot(a, b) / (||a||*||b||) = dot(a, b)).")
    print("Euclidean distance is also monotonically related to cosine similarity: L2(a, b) = sqrt(2 - 2 * cos_sim(a, b)).")
    print("Since L2 distance decreases as similarity increases, sorting by -Euclidean distance produces")
    print("the exact same rank ordering as sorting by cosine similarity. Thus, the metrics will never disagree.")
    print()

def run_exercise_2():
    print("=" * 70)
    print("EXERCISE 2: Chunk Size Experiment")
    print("=" * 70)
    
    chunk_sizes = [20, 50, 100, 200, 500]
    
    print(f"{'Chunk Size':<12} | {'Total Chunks':<12} | {'Avg Top-1 Score':<18} | {'Individual Top-1 Scores'}")
    print("-" * 80)
    
    for size in chunk_sizes:
        overlap = max(5, size // 5)
        engine = SemanticSearchEngine(chunk_size=size, overlap=overlap)
        num_chunks = engine.index_documents(SAMPLE_DOCUMENTS, SOURCE_NAMES)
        
        scores = []
        for query in QUERIES:
            res = engine.search(query, top_k=1)
            scores.append(res[0]["score"] if res else 0.0)
            
        avg_score = np.mean(scores)
        scores_str = ", ".join([f"{s:.4f}" for s in scores])
        print(f"{size:<12d} | {num_chunks:<12d} | {avg_score:<18.4f} | {scores_str}")
        
    print("\n--- Analysis Summary ---")
    print("Observations:")
    print("1. Small chunks (e.g., 20 words) lead to more chunks, but the vocabulary representation is extremely sparse.")
    print("   This can make the TF-IDF representation less robust because query terms might not match exactly within")
    print("   a very narrow context, or conversely, a tiny chunk with a matching keyword gets a high score but lacks context.")
    print("2. Large chunks (e.g., 200 or 500 words) pack more text into a single embedding vector.")
    print("   Since the TF-IDF vector is normalized, embedding a very long text averages out the specific keywords,")
    print("   diluting the contribution of any single important term (vocabulary dilution).")
    print("3. There is a sweet spot (around 50-100 words in this simple TF-IDF embedder) where the text has enough context")
    print("   to match query terms reliably without diluting the semantic focus. In production models, this sweet spot is")
    print("   typically 256-512 tokens.")
    print()

def run_exercise_3():
    print("=" * 70)
    print("EXERCISE 3: Matryoshka Simulation")
    print("=" * 70)
    
    # 1. Fit the SimpleEmbedder on the chunked sample documents
    # and pad the vocab to exactly 500 dimensions.
    engine = SemanticSearchEngine(chunk_size=30, overlap=5)
    
    # We will manually build the padded embedder
    all_chunks = []
    for doc in SAMPLE_DOCUMENTS:
        all_chunks.extend(chunk_text(doc, chunk_size=30, overlap=5))
        
    # Fit
    embedder = SimpleEmbedder()
    embedder.fit(all_chunks)
    
    # Pad to 500 dimensions
    current_vocab_size = len(embedder.vocab)
    if current_vocab_size < 500:
        padding_needed = 500 - current_vocab_size
        for i in range(padding_needed):
            dummy_word = f"__dummy_word_{i}__"
            embedder.vocab.append(dummy_word)
            embedder.word_to_idx[dummy_word] = current_vocab_size + i
        default_idf = math.log((len(all_chunks) + 1) / 1) + 1
        embedder.idf = np.concatenate([embedder.idf, np.full(padding_needed, default_idf)])
    
    # Build vector index
    index = VectorIndex()
    for chunk in all_chunks:
        vec = embedder.embed(chunk)
        index.add(vec, chunk)
        
    truncation_dims = [50, 100, 200, 500]
    k = 3
    
    # Get ground truth (top-3 at full 500 dimensions)
    ground_truth = {}
    for q_idx, query in enumerate(QUERIES):
        q_vec = embedder.embed(query)
        res = index.search(q_vec, top_k=k, metric="cosine")
        ground_truth[q_idx] = [r["index"] for r in res]
        
    print(f"Measuring Recall@{k} relative to full 500-d embeddings:")
    print("-" * 60)
    
    for dim in truncation_dims:
        recalls = []
        for q_idx, query in enumerate(QUERIES):
            q_vec = embedder.embed(query)
            
            # Truncate and re-normalize the query
            q_vec_trunc = truncate_embedding(q_vec, dim)
            
            # Search over truncated vectors
            scores = []
            for i, vec in enumerate(index.vectors):
                vec_trunc = truncate_embedding(vec, dim)
                score = cosine_similarity(q_vec_trunc, vec_trunc)
                scores.append((i, score))
            scores.sort(key=lambda x: x[1], reverse=True)
            truncated_top_k = [x[0] for x in scores[:k]]
            
            # Calculate recall
            overlap = len(set(truncated_top_k) & set(ground_truth[q_idx]))
            recall = overlap / k
            recalls.append(recall)
            
        avg_recall = np.mean(recalls)
        print(f"Dimensions: {dim:>3d} | Average Recall@{k}: {avg_recall:.2%} (Individual: {recalls})")
        
    print("\n--- Analysis Summary ---")
    print("Observations:")
    print("1. Lower dimensions (50-100) experience recall drop because we discard dimensions representing terms in the vocabulary.")
    print("2. In standard Matryoshka representations (like OpenAI's text-embedding-3), the model is trained with a specialized loss")
    print("   function that forces earlier dimensions to encode the most critical semantic information. In our simple simulation,")
    print("   truncation is raw/random (sorted alphabetically by word), which is why we see a significant recall drop when too much")
    print("   vocabulary is discarded. In a real Matryoshka model, a 6x reduction in dimensions leads to only 3-5% recall drop.")
    print()

def run_exercise_4():
    print("=" * 70)
    print("EXERCISE 4: Binary Quantization")
    print("=" * 70)
    
    engine = SemanticSearchEngine(chunk_size=30, overlap=5)
    engine.index_documents(SAMPLE_DOCUMENTS, SOURCE_NAMES)
    
    k = 5
    overlaps = []
    
    print(f"{'Query':<50} | {'Cosine Indices':<20} | {'Hamming Indices':<20} | {'Overlap'}")
    print("-" * 105)
    
    for query in QUERIES:
        cosine_res = engine.search(query, top_k=k, metric="cosine")
        hamming_res = engine.search(query, top_k=k, metric="hamming")
        
        cosine_ids = [r["index"] for r in cosine_res]
        hamming_ids = [r["index"] for r in hamming_res]
        
        overlap = len(set(cosine_ids) & set(hamming_ids))
        overlaps.append(overlap)
        
        query_trunc = query if len(query) <= 48 else query[:45] + "..."
        print(f"{query_trunc:<50} | {str(cosine_ids):<20} | {str(hamming_ids):<20} | {overlap}/{k} ({overlap/k:.0%})")
        
    avg_overlap_pct = np.mean(overlaps) / k
    print(f"\nAverage Top-{k} overlap percentage: {avg_overlap_pct:.2%}")
    
    vocab_size = len(engine.embedder.vocab)
    storage_full = vocab_size * 4
    storage_binary = math.ceil(vocab_size / 8)
    print(f"\nStorage comparison per vector ({vocab_size} dimensions):")
    print(f"  - Float32: {storage_full} bytes")
    print(f"  - Binary (1-bit): {storage_binary} bytes")
    print(f"  - Storage reduction factor: {storage_full/storage_binary:.1f}x")
    
    print("\n--- Analysis Summary ---")
    print("Observations:")
    print("1. Binary quantization encodes floats to bits (1 if positive, 0 if negative).")
    print("2. The retrieval overlap shows that even with a simple TF-IDF sparse model binarized, we preserve some overlap.")
    print("3. In production models (dense embeddings), binary quantization retains >90% of retrieval recall while providing")
    print("   a 32x memory saving and massive speedup using hardware-accelerated Hamming distance (POPCNT instruction on CPU).")
    print()

def run_exercise_5():
    print("=" * 70)
    print("EXERCISE 5: Sentence-based Chunking vs Fixed-size Chunking")
    print("=" * 70)
    
    # Fixed-size engine
    fixed_engine = SemanticSearchEngine(chunk_size=50, overlap=10)
    fixed_engine.index_documents(SAMPLE_DOCUMENTS, SOURCE_NAMES)
    
    # Sentence-based engine
    # To implement sentence-based chunking, we need a SemanticSearchEngine subclass or logic
    # that overrides document chunking with chunk_by_sentences.
    class SentenceSemanticSearchEngine(SemanticSearchEngine):
        def index_documents(self, documents, source_names=None):
            all_chunks = []
            all_sources = []
            for i, doc in enumerate(documents):
                chunks = chunk_by_sentences(doc, max_chunk_tokens=self.chunk_size)
                all_chunks.extend(chunks)
                name = source_names[i] if source_names else f"doc_{i}"
                all_sources.extend([name] * len(chunks))
            self.embedder.fit(all_chunks)
            for chunk, source in zip(all_chunks, all_sources):
                vec = self.embedder.embed(chunk)
                self.index.add(vec, chunk, {"source": source})
            return len(all_chunks)

    sent_engine = SentenceSemanticSearchEngine(chunk_size=50, overlap=0)
    sent_engine.index_documents(SAMPLE_DOCUMENTS, SOURCE_NAMES)
    
    print(f"{'Query':<45} | {'Fixed-size Score (Top-1)':<25} | {'Sentence-based Score (Top-1)'}")
    print("-" * 105)
    
    for query in QUERIES:
        fixed_res = fixed_engine.search(query, top_k=1)
        sent_res = sent_engine.search(query, top_k=1)
        
        fixed_score = fixed_res[0]["score"] if fixed_res else 0.0
        sent_score = sent_res[0]["score"] if sent_res else 0.0
        
        query_trunc = query if len(query) <= 43 else query[:40] + "..."
        print(f"{query_trunc:<45} | {fixed_score:<25.4f} | {sent_score:.4f}")
        
    print("\n--- Detailed retrieved chunks comparison ---")
    for idx, query in enumerate(QUERIES[:2]):
        print(f"\nQuery: \"{query}\"")
        fixed_top = fixed_engine.search(query, top_k=1)[0]
        sent_top = sent_engine.search(query, top_k=1)[0]
        
        print(f"  Fixed-size top chunk [{fixed_top['metadata'].get('source')}]:")
        print(f"    \"{fixed_top['text']}\"")
        print(f"  Sentence-based top chunk [{sent_top['metadata'].get('source')}]:")
        print(f"    \"{sent_top['text']}\"")
        
    print("\n--- Analysis Summary ---")
    print("Observations:")
    print("1. Sentence-based chunking splits documents at sentence boundaries rather than cutting words mid-sentence.")
    print("2. This respects semantic units, ensuring complete thoughts are preserved in each chunk, which improves")
    print("   retrieval relevance and makes the retrieved context cleaner for consumption by an LLM in a RAG pipeline.")
    print("3. In contrast, fixed-size chunking may split a key sentence in half, causing the model to miss keywords or")
    print("   lose contextual meaning because half of the sentence lies in chunk A and the other half in chunk B.")
    print()

if __name__ == "__main__":
    run_exercise_1()
    run_exercise_2()
    run_exercise_3()
    run_exercise_4()
    run_exercise_5()
